version: 0.2

phases:
  pre_build:
    commands:
      - npm i
      - ./.make_credentials.sh

  build:
    commands:
      - npm run build

  post_build:
    commands:
      # Only taking care of deploy previews for now
      - aws s3 sync --delete public --profile staging "s3://staging.significa.co/previews/$(echo $CODEBUILD_WEBHOOK_TRIGGER | tr / -)"
      - echo https://$(echo $CODEBUILD_WEBHOOK_TRIGGER | tr / -).staging.significa.co/

artifacts:
  base-directory: public
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - .cache/*
    - node_modules/*
    - public/*
