# Date for order
date: 2018/01/02

seo:
  title: Mishmash by Signfica
  description: Mishmash is a minimal office supply brand.

# Main info
title: Mishmash
tagline: A minimal office supply brand
description: |
  mishmash keeps looking for new ways to design office supplies, contrasting a clear taste for the minimal with an elaborate and meticulous choice of materials. This is a detailed showcase on how we designed their website. 

# Images
hero: ./mishmash/2-Mishmash-MainImage.png
featured: ./mishmash/1-Mishmash-CoverImage.png
thumbnail: ./mishmash/1-Mishmash-CoverImage.png

# Settings
heroTheme: mishmash-grey
mainTheme: mishmash-light
navigationTheme: mishmash-light
themes:
  - name: mishmash-grey
    background: '#f0f0f0'
    foreground: '#242424'
    highlight: '#FF5050'
    medium: 'rgba(0,0,0,0.4)'
    subtle: '#b2b2b2'
    error: '#FF5050'

  - name: mishmash-light
    background: '#FFFFFF'
    foreground: '#242424'
    highlight: '#ff5050'
    medium: '#999999'
    subtle: '#b2b2b2'
    error: '#FF5050'

# Info
client: mishmash
services:
  - UI/UX
deliverables:
  - Website
  - Responsive
links:
  - link: https://mishmash.pt/
    linkText: Website

content:
  # Chapter
  - title: Website
    showTitle: false
    content:
      # Section
      - title: Design
        sections:
          # Sections

          - type: image
            layout: large
            margin: bottom
            content:
              image: ./mishmash/3-Mishmash-ShowOf.jpg

          - type: text
            content:
              title: Homepage
              text: |
                The doorway to the world of mishmash. Here we must engage the user and make sure he loves every mishmash product as much as we do. The precision of their products was matched by a precise grid that takes over and defines the entire design.

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/4-Mishmash-Homepage.png

          - type: video
            layout: large
            margin: both
            content:
              video: ./mishmash/5-Mishmash-HomepageAnimation.mp4
              autoplay: true
              loop: true
              controls: true
              muted: true

          - type: text
            content:
              title: Mobile Home Page
              text: |
                The same attention to detail was kept to ensure a great mobile experience for newcomers and returners alike. Encapsuled by the phone's screen, every mishmash product is allowed to shine.

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/6-Mishmash-Mobile.png

          - type: text
            content:
              title: Shop
              text: |
                Sort & filter every product and find the one that is right for you. You can sort by price and filter by color or size. With that, every focus is placed on the products where you can quickly decide which one is right for you.

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/7-Mishmash-Shop.png

          - type: text
            content:
              title: Product Page
              text: |
                Explore every little detail, with a high quality gallery, product specs, and reviews by your favourite bloggers. "Added to cart."

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/8-Mishmash-ProductPage.png

          - type: text
            content:
              title: Shop on the go
              text: |
                Browse, filter and appreciate every little detail of each mishmash product while you are on the move.

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/9-Mishmash-ShopOnTheGo.png

          - type: text
            content:
              title: Cart & Checkout
              text: |
                You probably fell in love with the product so why not fall in love with the entire checkout process? Also, why wait until you’re home to buy one of mishmash’s unique notebooks? You can do it anywhere!

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/10-Mishmash-Cart.png

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/11-Mishmash-CartMobile.png

          - type: text
            content:
              title: Blog
              text: |
                Let's say that mishmash is part of your life. But so are many other things. The blog is all about the things you love, even when travelling!

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/12-Mishmash-Blog.png

          - type: image
            layout: large
            margin: bottom
            content:
              image: ./mishmash/13-Mishmash-BlogMobile.png

          - type: testimonial
            theme: dark
            margin: both
            content:
              text: The website defined the way that people look at our products.
              author: Beatriz Barros, Founder

      - title: Styleguide
        sections:
          - type: text
            margin: top
            content:
              title: Color Palette
              text: |
                So the user can focus entirely on what trully matters — the products on sale, we used a greyscale palette on white background, using color only when extremely necessary. 

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/14-Mishmash-Colors.jpg

          - type: text
            content:
              title: Typography
              text: |
                Used as part of the Mishmash brand, the Circular font was already deeply embeded in its DNA. Used in three different weights — Book, Medium e Bold.

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/16-MishMash-Typography.jpg

          - type: text
            content:
              title: Iconography
              text: |
                With every mishmash product being unique, it was important to create a set of icons that can visually represent every specification and detail.       

          - type: image
            layout: large
            margin: both
            content:
              image: ./mishmash/15-Mishmash-Icons.jpg
