# Date for order
date: 2018/06/01

# Main info
title: Rocket.Chat
tagline: Open Source Team Communication
description: |
  Rocket.Chat is free, unlimited and open source as it replaces email & Slack as the ultimate team chat software solution. But what’s it like to design such a powerful open source platform?

# Images
hero: ./rocketchat/1-RocketChat-MainImage.png
featured: ./rocketchat/2-RocketChat-CoverImage.png
thumbnail: ./rocketchat/2-RocketChat-CoverImage.png

# Settings
heroTheme: rocketchat-blue
mainTheme: rocketchat-light
navigationTheme: rocketchat-light
themes:
  - name: rocketchat-blue
    background: '#030C19'
    foreground: '#fff'
    highlight: '#1D74F5'
    medium: '#A3B4CC'
    subtle: '#b2b2b2'
    error: '#FF5050'

  - name: rocketchat-light
    background: '#FFFFFF'
    foreground: '#0B182B'
    highlight: '#1D74F5'
    medium: '#b2b2b2'
    subtle: '#b2b2b2'
    error: '#FF5050'

  - name: rocketchat-grey
    background: '#F3F5F8'
    foreground: '#0B182B'
    highlight: '#1D74F5'
    medium: '#b2b2b2'
    subtle: '#b2b2b2'
    error: '#FF5050'

# Info
client: RocketChat
services:
  - UI/UX
  - Front-End
  - Illustration
deliverables:
  - Web App
  - Mobile Apps
  - Website 
  - Illustration
links:
  - link: https://rocket.chat/
    linkText: Website

content:
  # Chapter
  - title: The App
    showTitle: false
    content:
      # Section
      - title: StyleGuide
        sections:
          # Sections
          
          - type: image
            layout: medium
            margin: bottom
            content:
              image: ./rocketchat/3-RocketChat-Devices.png
          
          - type: text
            content:
              title: Open Source Community
              text: |
                With over 20k stars on GitHub, more than 600 contributors and over 13k commits, Rocket.Chat is the largest and most active open source team chat community.
              link:
                url: https://github.com/RocketChat/Rocket.Chat
                text: View on GitHub

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/4-RocketChat-Illustration.png

          - type: text
            content:
              title: Native Typography
              text: |
                The design of every Rocket.Chat platform was created with native system fonts. Created with legibility at the core, these fonts will dynamically adapt to the platform’s specificity for unmatched performance.

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/5-RocketChat-Native.png

          - type: text
            content:
              title: Font Style
              text: |
                Used in 6 different sizes & 4 different weights — Regular, Medium, Semibold & Bold. Font color will vary depending on the used background — Dark, Light or Color.

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/6-RocketChat-Typography.png

          - type: text
            content:
              title: Color Palette
              text: |
                With Space as the backdrop, planets and stars bring this universe to life.  A mixture of strong & vibrant colors to contrast with the darkness of space.

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/7-RocketChat-Colors.png

          - type: text
            content:
              title: Iconography
              text: |
                A vast and diverse constellation of icons, carefully crafted to add visual context and enhance usability. Created in 3 different sizes to satisfy the most varied sections of the app.

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/8-RocketChat-Icons.png

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/9-RocketChat-Controls.png

      # Section
      - title: UI Components
        sections:

          - type: text
            content:
              title: Buttons & DropDownn
              text: |
                We believe in a well structured component based system that can effortlessly bridge the design and developement process. A single source of truth that serves as the backbone of Rocket.Chat.

          - type: image
            layout: small
            margin: bottom
            content:
              image: ./rocketchat/10-RocketChat-Details.png

          - type: image
            layout: small
            margin: top
            content:
              image: ./rocketchat/11-RocketChat-Buttons.png

          - type: image
            layout: small
            margin: both
            content:
              image: ./rocketchat/12-RocketChat-LightBackground.png

          - type: image
            layout: small
            margin: bottom
            content:
              image: ./rocketchat/13-RocketChat-CheckBoxes.png

          - type: text
            margin: top
            theme: rocketchat-grey
            content:
              title: The Sidebar
              text: |
                Constructed with smaller independent components that together form a versatile, everchanging navigation bar that is paramount to the platform’s navigation.

          - type: image
            theme: rocketchat-grey
            layout: full
            margin: bottom
            content:
              image: ./rocketchat/14-RocketChat-SideBar.png

          - type: text
            theme: rocketchat-grey
            content:
              title: Endless components
              text: |
                Small pieces of a very complex puzzle, each with their own specificity, with various perks & permutations, come together to form Rocket.Chat. 

          - type: image
            theme: rocketchat-grey
            layout: full
            margin: bottom
            content:
              image: ./rocketchat/15-RocketChat-EndlessComponents.png

      # Section
      - title: The App
        sections:

          - type: text
            margin: top
            content:
              title: Desktop
              text: |
                Fully featured & fully customizable! The end product of our design process is in fact the foundation to the limitless possibilities of its open source nature.   

          - type: image
            layout: medium
            margin: both
            content:
              image: ./rocketchat/16-RocketChat-Desktop.png

          - type: sticky
            content:
              sticky: false
              invert: true
              title: Live Chat
              image: ./rocketchat/17-RocketChat-Chat.png
              text: |
                With Rocket.Chat LiveChat you can add real-time chat widgets to any website or mobile app and get more value from your team chat. Replace other systems and use one communication platform to save time and money. Create a user support helpdesk, answer customer queries and convert leads.

          - type: sticky
            content:
              sticky: false
              invert: false
              title: Video Calls
              image: ./rocketchat/18-RocketChat-Call.png
              text: |
                Rocket.Chat’s one-to-one or one-to-many high-quality video calling feature is simple, reliable, and works on all platforms. Improve your team’s communication with live, face-to-face video chat.

          - type: image
            layout: large
            margin: both
            content:
              image: ./rocketchat/19-RocketChat-VideoCall.png

          - type: image
            layout: full
            margin: top
            content:
              image: ./rocketchat/20-RocketChat-Grid.png

          - type: video
            theme: rocketchat-grey
            layout: large
            margin: both
            content:
              video: ./rocketchat/28-RocketChat-MobileAnimation.mp4
              autoplay: true
              loop: true
              controls: false
              muted: true

          - type: image
            theme: rocketchat-grey
            layout: medium
            margin: both
            content:
              image: ./rocketchat/29-RocketChat-MobileSection.png

          - type: text
            theme: rocketchat-grey
            content:
              title: Customisation
              text: |
                Customise your platform to tailor its exact look & feel by adding or removing features and selecting your own integrations, plugins & themes.

          - type: image
            theme: rocketchat-grey
            layout: medium
            margin: both
            content:
              image: ./rocketchat/21-RocketChat-Screens.png

          - type: text
            theme: rocketchat-grey
            content:
              title: More Costumisation
              text: |
                Change the font, its size, color & weight. Change the background color or add your unique family of icons. Endless customisationpossibilities to make Rocket.Chat your own.

          - type: image
            theme: rocketchat-grey
            layout: full
            margin: top
            content:
              image: ./rocketchat/22-RocketChat-Screens02.png

  # Chapter
  - title: The Website
    showTitle: false
    content:
      # Section
      - title: Design
        sections:

          - type: text
            margin: top
            theme: rocketchat-blue
            content:
              title: Website
              text: |
                The gateway to a fantastic open source community that comes together for the future of team communication.

          - type: image
            theme: rocketchat-blue
            layout: full
            margin: bottom
            content:
              image: ./rocketchat/23-RocketChat-Launch.png

          - type: image
            theme: rocketchat-blue
            layout: full
            content:
              image: ./rocketchat/24-RocketChat-Website.png

          - type: image
            theme: rocketchat-blue
            layout: medium
            content:
              image: ./rocketchat/25-RocketChat-Grid02.png

          - type: text
            theme: rocketchat-blue
            content:
              title: Light/Dark
              text: |
                In productivity-led areas of the website, we allow the user to opt for their viewing preferences.

          - type: video
            theme: rocketchat-blue
            layout: medium
            margin: both
            content:
              video: ./rocketchat/26-lightvsdark.mp4
              autoplay: true
              loop: true
              controls: false
              muted: true

          - type: image
            theme: rocketchat-blue
            layout: medium
            margin: both
            content:
              image: ./rocketchat/27-RocketChat-Remate.png